#!/usr/bin/env python3

import subprocess
import argparse
import platform
import shutil
import errno
import sys
import os

from pathlib import Path
from collections import namedtuple
from fuse import FUSE, FuseOSError, Operations

# TODO: parent permissions for:
#	 mknod, rmdir, mkdir, unlink, symlink, rename (x2), link, utimens
# TODO: Long term things:
#       1. thread safe
#       2. optimize by only storing top level in shadow
#       3. Relative symlinks are treated as cross-device symlinks

# The class that handles all FS / File operations
class LayerFS(Operations):
    def __init__(self, root, layer_storage, mountpoint,
            allow_hardlinks, allow_cd_symlinks):
        # Make directories
        layer_storage = os.path.normpath(layer_storage)
        Path(layer_storage).mkdir(parents=False, exist_ok=True)
        self.fake_root = self.join(layer_storage, 'fake_root')
        Path(self.fake_root).mkdir(parents=True, exist_ok=True)
        # Setup LayerFS
        self.allow_hardlinks = allow_hardlinks
        self.allow_cd_symlinks = allow_cd_symlinks
        self.fd_map_t = namedtuple('fd_map_t', ['fd', 'path', 'open_args'])
        self.shadow_file = self.join(layer_storage, 'shadow')
        self.root = os.path.normpath(root)
        self.mountpoint = mountpoint
        self.load_shadow()
        self.fd_map = {}

    ######################################################################
    #                                                                    #
    #                          Helper Functions                          #
    #                                                                    #
    ######################################################################

    ########################################
    #      Path Construction Functions     #
    ########################################

    # Load shadow from a file
    def load_shadow(self):
        if not os.path.exists(self.shadow_file):
            self.shadow = set()
        else:
            with open(self.shadow_file) as f:
                data = f.read()
            self.shadow = set([ i for i in data.split('\n') if len(i) > 0 ])

    # Never end in slash
    @staticmethod
    def join(a_root, tail):
        while tail.startswith('/'):
            tail = tail[1:]
        joined = os.path.join(a_root, tail)
        return os.path.normpath(joined)

    # Never end in slash
    def real_path(self, partial):
        return self.join(self.root, partial)

    # Never end in slash
    def fake_path(self, partial):
        return self.join(self.fake_root, partial)

    ########################################
    #           Shadow Functions           #
    ########################################

    # Add something to shadow (the fake paths to be used)
    def add_to_shadow(self, partial):
        self.shadow.add(partial)
        with open(self.shadow_file, 'a') as f:
            f.write(partial + '\n')

    # Determine if the real or fake paths should be used
    def test_use_fake(self, partial):
        if partial in self.shadow:
            return True
        elif partial == '/':
            return False
        else:
            return self.test_use_fake(os.path.dirname(partial))

    ########################################
    #       Path Selection Functions       #
    ########################################

    # Used for copytree to ignore already fake sub-items
    def ignore_fake(self, d, children):
        assert d.startswith(self.root), 'sanity check'
        prepend = d[len(self.root):]
        return [ i for i in children if self.test_use_fake(self.join(prepend, i)) ]

    def copy_file(self, *args):
        return shutil.copy2(*args, follow_symlinks=False)

    # Returns path to use following these rules
    # force_fake will copy over real files if needed
    # Note: ancestors are not promised to have the proper permissions
    def path(self, partial, *, force_fake):
        use_fake = self.test_use_fake(partial)
        if use_fake is False and force_fake is True:
            path = self.fake_path(partial)
            Path(os.path.dirname(path)).mkdir(parents=True, exist_ok=True)
            real_path = self.real_path(partial)
            if os.path.lexists(real_path):
                if os.path.isdir(real_path) and not os.path.islink(real_path):
                    shutil.copytree(real_path, path, copy_function=self.copy_file,
                                    ignore=self.ignore_fake, dirs_exist_ok=True)
                else:
                    self.copy_file(real_path, path)
            self.add_to_shadow(partial)
            return path
        return self.fake_path(partial) if use_fake else self.real_path(partial)

    ########################################
    #             fd Functions             #
    ########################################

    # Add an OS fd to the fdmap, return the LayerFS fd
    def add_to_fd_map(self, path, fd, *open_args):
        fake_fd = 0
        while fake_fd in self.fd_map:
            fake_fd += 1
        self.fd_map[fake_fd] = self.fd_map_t(fd, path, open_args)
        return fake_fd

    # Translate a LayerFS fs to an OS fd
    # Will update the OS fd if needed
    def real_fd(self, fh, path):
        entry = self.fd_map[fh]
        if entry.path == path:
            return entry.fd
        os.close(entry.fd)
        fd = os.open(entry.path, *entry.open_args)
        self.fd_map[fh].fd = fd
        return fd

    ########################################
    #            Misc Functions            #
    ########################################

    @staticmethod
    def fassert(b, ec):
        if not b:
            raise FuseOSError(ec)

    # Return the directory entries of partial
    # Does not include '.' or '..'
    def ls_dir(self, partial):
        fake_path = self.fake_path(partial)
        path = self.path(partial, force_fake=False)
        if fake_path == path:
            return os.listdir(path)
        else:
            # Check for path validity
            self.fassert(os.path.exists(path), errno.ENOENT)
            self.fassert(os.path.isdir(path), errno.ENOTDIR)
            # Get both real and fake files
            real_partials = [ self.join(partial, i) for i in os.listdir(path) ]
            real_files = [ self.path(i, force_fake=False) for i in real_partials ]
            fake_files = [ self.fake_path(i) for i in self.shadow if os.path.dirname(i) == partial ]
            # Merge and return the ones that should exist
            ret = [ os.path.basename(i) for i in (real_files + fake_files) if os.path.lexists(i) ]
            return list(set(ret))

    ######################################################################
    #                                                                    #
    #                         Filesystem Methods                         #
    #                                                                    #
    ######################################################################

    def access(self, partial, mode):
        path = self.path(partial, force_fake=False)
        self.fassert(os.access(path, mode), errno.EACCES)

    def chmod(self, partial, mode):
        path = self.path(partial, force_fake=True)
        os.chmod(path, mode)

    def chown(self, partial, uid, gid):
        partial = self.path(partial, force_fake=True)
        os.chown(path, uid, gid)

    def getattr(self, partial, fh=None):
        path = self.path(partial, force_fake=False)
        st = os.lstat(path)
        # TODO: fix these
        return dict((key, getattr(st, key)) for key in ('st_atime', 'st_ctime',
                'st_mtime', 'st_uid', 'st_gid', 'st_mode', 'st_size', 'st_nlink'))

    def readdir(self, partial, fh):
        dirents = self.ls_dir(partial)
        for i in ([ '.', '..' ] + dirents):
            yield i

    def readlink(self, partial):
        path = self.path(partial, force_fake=False)
        ret = os.path.normpath(os.readlink(path))
        # Adjust link
        # Below we do not use ret.replace in case self.root == '/'
        if ret.startswith(self.root):
            ret = self.join(self.mountpoint, ret[len(self.root):])
        elif ret.startswith(self.fake_root):
            ret = self.join(self.mountpoint, ret[len(self.fake_root):])
        # Ensure no cross-device links or relative links
        if not ret.startswith(self.mountpoint) or not ret.startswith('/'):
            self.fassert(self.allow_cd_symlinks, errno.EXDEV)
        return ret

    def mknod(self, partial, mode, dev):
        path = self.path(partial, force_fake=True)
        os.mknod(path, mode, dev)

    def rmdir(self, partial):
        path = self.path(partial, force_fake=True)
        os.rmdir(path)

    def mkdir(self, partial, mode):
        path = self.path(partial, force_fake=True)
        os.mkdir(path, mode)

    def statfs(self, partial):
        path = self.path(partial, force_fake=False)
        stv = os.statvfs(path)
        return dict((key, getattr(stv, key)) for key in ('f_bavail', 'f_bfree',
            'f_blocks', 'f_bsize', 'f_favail', 'f_ffree', 'f_files', 'f_flag',
            'f_frsize', 'f_namemax'))

    def unlink(self, partial):
        path = self.path(partial, force_fake=True)
        os.unlink(path)

    def symlink(self, dst_partial, src):
        src = os.path.normpath(src)
        same_vol = src.startswith(self.mountpoint) and src.startswith('/')
        self.fassert(same_vol or self.allow_cd_symlinks, errno.EXDEV)
        os.symlink(src, self.path(dst_partial, force_fake=True))

    def rename(self, partial_old, partial_new):
        old = self.path(partial_old, force_fake=True)
        new = self.path(partial_new, force_fake=True)
        os.rename(old, new)

    def link(self, dst_partial, src_partial):
        if self.allow_hardlinks:
            src = self.path(src_partial, force_fake=True)
            dst = self.path(dst_partial, force_fake=True)
            os.link(src, dst)

    def utimens(self, partial, times=None):
        path = self.path(partial, force_fake=True)
        os.utime(path, times)

    ######################################################################
    #                                                                    #
    #                            File Methods                            #
    #                                                                    #
    ######################################################################

    def open(self, partial, flags):
        req_write = [ os.O_WRONLY, os.O_RDWR, os.O_CREAT, os.O_APPEND, os.O_TRUNC, os.O_EXCL ]
        write_access = any([ flags == (flags | i) for i in req_write ])
        path = self.path(partial, force_fake=write_access)
        fd = os.open(path, flags)
        return self.add_to_fd_map(path, fd)

    def create(self, partial, mode, fi=None):
        path = self.path(partial, force_fake=True)
        fd = os.open(path, os.O_WRONLY | os.O_CREAT, mode)
        return self.add_to_fd_map(path, fd)

    def read(self, partial, length, offset, fh):
        path = self.path(partial, force_fake=False)
        fd = self.real_fd(fh, path)
        os.lseek(fd, offset, os.SEEK_SET)
        return os.read(fd, length)

    def write(self, partial, buf, offset, fh):
        path = self.path(partial, force_fake=True)
        fd = self.real_fd(fh, path)
        os.lseek(fd, offset, os.SEEK_SET)
        return os.write(fd, buf)

    def truncate(self, partial, length, fh=None):
        path = self.path(partial, force_fake=True)
        with open(path, 'r+') as f:
            f.truncate(length)

    def flush(self, partial, fh):
        pass

    def release(self, partial, fh):
        fd = self.fd_map.pop(fh)
        os.close(fd.fd)

    def fsync(self, partial, fdatasync, fh):
        path = self.path(partial, force_fake=True)
        fd = self.real_fd(fh, path)
        os.fsync(fd)


def layerFS(src, layer_storage, mountpoint, fuse_args, allow_ls_in_src, **layerfs_args):
    # Argument verification
    src = os.path.realpath(src)
    mountpoint = os.path.abspath(mountpoint)
    layer_storage = os.path.realpath(layer_storage)
    try:
        if not allow_ls_in_src:
            assert not layer_storage.startswith(src), \
                'layer_storage cannot be within src without the --allow_ls_in_src flag'
        assert len(set([src, layer_storage, os.path.realpath(mountpoint)])) == 3, \
            'src, layer_storage, and mountpoint cannot be the same'
        assert os.path.exists(src), src + ' does not exist'
        assert os.path.isdir(src), src + ' is not a directory'
        if os.path.exists(layer_storage):
            assert os.path.isdir(layer_storage), layer_storage + ' exists and is not a directory'
    except AssertionError as e:
        print('Error: ' + str(e))
        sys.exit(1)
    # Install the FUSE
    FUSE(LayerFS(src, layer_storage, mountpoint, **layerfs_args), mountpoint, **fuse_args)

def parse_args(prog, *args):
    osx = 'Darwin' == platform.system()
    parser = argparse.ArgumentParser(prog=os.path.basename(prog))
    # Positional args
    parser.add_argument('src', help='The root of what LayerFS should layer')
    parser.add_argument('layer_storage', help='A directory LayerFS can store it\'s filesystem diffs')
    parser.add_argument('mountpoint', help='Where to mount the LayerFS')
    # Optional args
    parser.add_argument('--allow_hardlinks', action='store_true', default=False, help='Allow hardlinks')
    parser.add_argument('--allow_ls_in_src', action='store_true', default=False,
        help='Allow persist to be within src')
    parser.add_argument('--allow_cd_symlinks', action='store_true', default=False,
        help='Allow cross-device symlinks between LayerFS' + \
             ' and other filesystems such as the host filesystem')
    # Fuse args
    fuse = parser.add_argument_group('optional fuse arguments')
    fuse.add_argument('--allow_other', action='store_true', default=False,
        help='This option overrides the security measure restricting file access to ' + \
             'the filesystem owner, so that all users (including root) can access the files.')
    fuse.add_argument('--foreground', action='store_true', default=False,
        help='Keep the script alive.')
    fuse.add_argument('--nothreads', action='store_true', default=False,
        help='Promise that only one thread will ever use the json FS')
    fuse.add_argument('--debug', action='store_true', default=False,
        help='Show every interaction with the json FS')
    if osx:
        fuse.add_argument('--volname', action='store', default=None,
            help='Mac volume name. Default = <mountpoint>')
    # Parse args
    args = vars(parser.parse_args(args))
    if osx:
        if args['volname'] is None:
            args['volname'] = args['mountpoint']
    fuse_keys = [ i.dest for i in fuse._group_actions ]
    fuse_args = { i:args[i] for i in fuse_keys }
    main_args = { i:k for i,k in args.items() if i not in fuse_keys }
    return main_args, fuse_args

def main(argv):
    main_args, fuse_args = parse_args(*argv)
    return layerFS(**main_args, fuse_args=fuse_args)


# Don't run on import
if __name__ == '__main__':
    rv = main(sys.argv)
    if type(rv) is int:
        sys.exit(rv)
